#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsoncpp
Version  : 1.9.5
Release  : 13
URL      : https://github.com/open-source-parsers/jsoncpp/archive/1.9.5/jsoncpp-1.9.5.tar.gz
Source0  : https://github.com/open-source-parsers/jsoncpp/archive/1.9.5/jsoncpp-1.9.5.tar.gz
Summary  : A C++ library for interacting with JSON
Group    : Development/Tools
License  : MIT
Requires: jsoncpp-lib = %{version}-%{release}
Requires: jsoncpp-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : python3
BuildRequires : python3-dev

%description
# JsonCpp
[![badge](https://img.shields.io/badge/conan.io-jsoncpp%2F1.8.0-green.svg?logo=data:image/png;base64%2CiVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAMAAAAolt3jAAAA1VBMVEUAAABhlctjlstkl8tlmMtlmMxlmcxmmcxnmsxpnMxpnM1qnc1sn85voM91oM11oc1xotB2oc56pNF6pNJ2ptJ8ptJ8ptN9ptN8p9N5qNJ9p9N9p9R8qtOBqdSAqtOAqtR%2BrNSCrNJ/rdWDrNWCsNWCsNaJs9eLs9iRvNuVvdyVv9yXwd2Zwt6axN6dxt%2Bfx%2BChyeGiyuGjyuCjyuGly%2BGlzOKmzOGozuKoz%2BKqz%2BOq0OOv1OWw1OWw1eWx1eWy1uay1%2Baz1%2Baz1%2Bez2Oe02Oe12ee22ujUGwH3AAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgBQkREyOxFIh/AAAAiklEQVQI12NgAAMbOwY4sLZ2NtQ1coVKWNvoc/Eq8XDr2wB5Ig62ekza9vaOqpK2TpoMzOxaFtwqZua2Bm4makIM7OzMAjoaCqYuxooSUqJALjs7o4yVpbowvzSUy87KqSwmxQfnsrPISyFzWeWAXCkpMaBVIC4bmCsOdgiUKwh3JojLgAQ4ZCE0AMm2D29tZwe6AAAAAElFTkSuQmCC)](https://bintray.com/theirix/conan-repo/jsoncpp%3Atheirix)
[![badge](https://img.shields.io/badge/license-MIT-blue)](https://github.com/open-source-parsers/jsoncpp/blob/master/LICENSE)
[![badge](https://img.shields.io/badge/document-doxygen-brightgreen)](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html)
[![Coverage Status](https://coveralls.io/repos/github/open-source-parsers/jsoncpp/badge.svg?branch=master)](https://coveralls.io/github/open-source-parsers/jsoncpp?branch=master)

%package dev
Summary: dev components for the jsoncpp package.
Group: Development
Requires: jsoncpp-lib = %{version}-%{release}
Provides: jsoncpp-devel = %{version}-%{release}
Requires: jsoncpp = %{version}-%{release}

%description dev
dev components for the jsoncpp package.


%package lib
Summary: lib components for the jsoncpp package.
Group: Libraries
Requires: jsoncpp-license = %{version}-%{release}

%description lib
lib components for the jsoncpp package.


%package license
Summary: license components for the jsoncpp package.
Group: Default

%description license
license components for the jsoncpp package.


%prep
%setup -q -n jsoncpp-1.9.5
cd %{_builddir}/jsoncpp-1.9.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672178352
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1672178352
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsoncpp
cp %{_builddir}/jsoncpp-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/jsoncpp/db16de9f0016978749716482a56ddec474b7d0b7
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/objects-RelWithDebInfo/jsoncpp_object/json_reader.cpp.o
/usr/lib64/objects-RelWithDebInfo/jsoncpp_object/json_value.cpp.o
/usr/lib64/objects-RelWithDebInfo/jsoncpp_object/json_writer.cpp.o

%files dev
%defattr(-,root,root,-)
/usr/include/json/allocator.h
/usr/include/json/assertions.h
/usr/include/json/config.h
/usr/include/json/forwards.h
/usr/include/json/json.h
/usr/include/json/json_features.h
/usr/include/json/reader.h
/usr/include/json/value.h
/usr/include/json/version.h
/usr/include/json/writer.h
/usr/lib64/cmake/jsoncpp/jsoncpp-namespaced-targets.cmake
/usr/lib64/cmake/jsoncpp/jsoncpp-targets-relwithdebinfo.cmake
/usr/lib64/cmake/jsoncpp/jsoncpp-targets.cmake
/usr/lib64/cmake/jsoncpp/jsoncppConfig.cmake
/usr/lib64/cmake/jsoncpp/jsoncppConfigVersion.cmake
/usr/lib64/libjsoncpp.so
/usr/lib64/pkgconfig/jsoncpp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjsoncpp.so.1.9.5
/usr/lib64/libjsoncpp.so.25

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsoncpp/db16de9f0016978749716482a56ddec474b7d0b7
